### ISSUE TITLE
Issue after auto upgrade faker dependency from 3.0.1 to 3.1.0

### ISSUE THREAD

**Issue by michalad** [json-schema-faker/json-schema-faker#116]
Hi,

Today, I've noticed following issue:
Error: self.number is not a function in /properties/xxxId

For schema:
        "xxxId": {
            "type": "string",
            "faker": "random.uuid"
        },

After investigation, it turned out, it is because  faker was was auto updated from 3.0.1 to 3.1.0. (In your package.json its value is set to "faker": "^3.0.1" so it allows auto updates)

Could you investigate it ? For now, I manually downgraded faker version to 3.0.1

Thanks!

**Comment by ducin** [comment]
@michalad thank you very much for your submission. Seems like this error might really happen and we should modify the versions to be either `~...` or even `=...`. I will investigate it ASAP.

**Comment by ducin** [comment]
Confirmed, I get exactly the same:

```
> jsf(schema)
Error: self.number is not a function in /
    at generate (C:\Users\tomasz.ducin\Development\Tests\jsf-test\node_modules\json-schema-faker\lib\jsf.js:74:13)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
```

**Comment by ducin** [comment]
Dzięki @michalad :)
New version `0.2.13` has been released and solves the problem quickly. We'll carry on with providing support for `faker@3.0.1`, perhaps the API changed.

**Comment by michalad** [comment]
Nie ma za co @ducin :)

Thanks for very quick solution for this issue. I'll try new version tomorrow :)
