### ISSUE TITLE
2 tests failing undeterministically

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#131]
```
> json-schema-faker@0.2.15 dev:spec C:\Users\tomasz.ducin\Development\json-schema-faker\json-schema-faker
> jasmine-node spec --coffee --noStackTrace --captureExceptions

..........F.............................................F...........

Failures:

  1) mixin issues with allOf (C:/Users/tomasz.ducin/Development/json-schema-faker/json-schema-faker/spec/core/issues/issue-57.json) should get combined as expected
    Message:
      Missing required property: state
Missing required property: city
Missing required property: street_address
ValidationError: Missing required property: street_address
missing: street_address,city,state

  2) generated object values (C:/Users/tomasz.ducin/Development/json-schema-faker/json-schema-faker/spec/core/types/objects.json) should handle additionalProperties
    Message:
      Too many properties defined (32), maximum 30
ValidationError: Too many properties defined (32), maximum 30
Invalid schema {"do7636da":"anim aute","nullac5c8":"dolore","pariatura39b6c":"amet et reprehenderit","incididunt0347e4c":"dolor exercitation est","cillumb2b1284":"eu eiusmod fugiat","velit0084e16":"ullamco esse fugiat","laboreb7dd81":"enim do occaecat","ut8eb8":"adipisicing commodo","voluptatea557":"reprehenderit consequat tempor","eua9622d7":"incididunt elit adipisicing","ametcd9ae30":"dolore est Duis","deserunt49bdbb4":"exercitation reprehenderit","aliquae4ffe8":"est","anim23910d":"occaecat","sunt13c10":"labore","laborumd563":"in","eiusmodc58557":"dolore ut est ea","nostrud5b3f0":"dolore velit in","irurebebbccd":"Lorem","occaecat2682":"ut do","Ut93d03":"commodo consequat","mollit72ef9":"do mollit labore","laboris16e1":"dolor","nisi5a4db55":"magna culpa","aute4bb2":"amet nostrud","minim7494":"pariatur ex enim est","Lorem09c84fa":"in ut aliqua ex","est0c8c1de":"magna dolor","quiea952":"ullamco minim","dolor7b7a":"in","commodo5a46":"elit eu","reprehenderitc39bd6e":"laborum Duis Lorem"}

Finished in 0.466 seconds
68 Tests, 2 Failures, 0 Skipped
```

They fail randomly. @pateketrueke do you know what is causing this behavior?

**Comment by ducin** [comment]
It's crazy, I get it all the time ;)

![image](https://cloud.githubusercontent.com/assets/375027/14360058/ccbdaeca-fcf4-11e5-846a-e6d77726fc27.png)

```
> json-schema-faker@0.3.0 cover /home/travis/build/json-schema-faker/json-schema-faker
> istanbul cover --root lib --x '**/spec/**' -- jasmine-node --coffee spec
.........................................................F...........
Failures:
  1) generated object values (core/types/objects.json) should handle additionalProperties
    Message:
      Too many properties defined (32), maximum 30
ValidationError: Too many properties defined (32), maximum 30
Invalid schema {"tempor1ad9ba":"ipsum aliqua esse fugiat","adf308ad8":"Lorem ut ut","ex184bd":"cupidatat laboris deserunt","sed61bab10":"Excepteur i","aute8744e0":"proident","ut2318":"aute","enima54e":"magna","ipsum31b6":"et aliquip labo","eiusmode455f":"Excepteur quis","esse52478":"esse Ut dolor culpa","pariatur50fc0d5":"sed aliquip aliqua laborum","dolor82aa9e":"laborum in mollit ad","officia5686":"exercitation occaecat","dolorafa3d":"deserunt","nisiae9b7":"cillum deserunt qui","Loremf2b01":"proident nulla laboris","aliquae27fe":"dolore exercitation Duis","quis64371":"exercitation commodo dolore","Utfb3a78f":"veniam magna","non5738d":"non","laborumb8a1b06":"in ut","anim7c0149":"consectetur aliquip aute in","culpa3f7bd":"id","sintf7a94":"ullamco dolore nulla in","irure3a6f8c3":"cillum in","commodo60395":"elit incididunt","veniambc480":"in","fugiat8c26fcb":"anim ut aliqua","exercitationd9b515":"eiusmod Ut et","estd0de":"culpa id dolore","dolorebe6d18e":"commodo","ullamco906e9":"consequat deserunt"}
    Stacktrace:
      Error: Too many properties defined (32), maximum 30
ValidationError: Too many properties defined (32), maximum 30
Invalid schema {"tempor1ad9ba":"ipsum aliqua esse fugiat","adf308ad8":"Lorem ut ut","ex184bd":"cupidatat laboris deserunt","sed61bab10":"Excepteur i","aute8744e0":"proident","ut2318":"aute","enima54e":"magna","ipsum31b6":"et aliquip labo","eiusmode455f":"Excepteur quis","esse52478":"esse Ut dolor culpa","pariatur50fc0d5":"sed aliquip aliqua laborum","dolor82aa9e":"laborum in mollit ad","officia5686":"exercitation occaecat","dolorafa3d":"deserunt","nisiae9b7":"cillum deserunt qui","Loremf2b01":"proident nulla laboris","aliquae27fe":"dolore exercitation Duis","quis64371":"exercitation commodo dolore","Utfb3a78f":"veniam magna","non5738d":"non","laborumb8a1b06":"in ut","anim7c0149":"consectetur aliquip aute in","culpa3f7bd":"id","sintf7a94":"ullamco dolore nulla in","irure3a6f8c3":"cillum in","commodo60395":"elit incididunt","veniambc480":"in","fugiat8c26fcb":"anim ut aliqua","exercitationd9b515":"eiusmod Ut et","estd0de":"culpa id dolore","dolorebe6d18e":"commodo","ullamco906e9":"consequat deserunt"}
  at Object.<anonymous> (/home/travis/build/json-schema-faker/json-schema-faker/spec/main-spec.coffee:72:30)
  at Timer.listOnTimeout (timers.js:119:15)
```

```
> json-schema-faker@0.3.0 cover /home/travis/build/json-schema-faker/json-schema-faker
> istanbul cover --root lib --x '**/spec/**' -- jasmine-node --coffee spec
...........F.........................................................
Failures:
  1) mixin issues with allOf (core/issues/issue-57.json) should get combined as expected
    Message:
      Missing required property: state
Missing required property: city
Missing required property: street_address
ValidationError: Missing required property: street_address
missing: street_address,city,state
    Stacktrace:
      Error: Missing required property: state
Missing required property: city
Missing required property: street_address
ValidationError: Missing required property: street_address
missing: street_address,city,state
  at Object.<anonymous> (/home/travis/build/json-schema-faker/json-schema-faker/spec/main-spec.coffee:72:30)
  at Object.jasmineEnv.executeSpecsInFolder (/home/travis/build/json-schema-faker/json-schema-faker/node_modules/jasmine-node/lib/jasmine-node/jasmine-loader.js:130:13)
  at Object.runSpecs (/home/travis/build/json-schema-faker/json-schema-faker/node_modules/jasmine-node/lib/jasmine-node/runner.js:179:13)
  at Object.<anonymous> (/home/travis/build/json-schema-faker/json-schema-faker/node_modules/jasmine-node/bin/jasmine-node:10:12)
  at Module._compile (module.js:430:26)
  at Object.Module._extensions..js (module.js:448:10)
  at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/lib/hook.js:109:37)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:471:10)
  at runFn (/home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
  at /home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
  at /home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/lib/util/file-matcher.js:68:16
  at /home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/node_modules/async/lib/async.js:52:16
  at /home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/node_modules/async/lib/async.js:361:13
  at /home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/node_modules/async/lib/async.js:52:16
  at done (/home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
  at /home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/node_modules/async/lib/async.js:44:16
  at /home/travis/build/json-schema-faker/json-schema-faker/node_modules/istanbul/node_modules/async/lib/async.js:358:17
  at LOOP (fs.js:1529:14)
  at doNTCallback0 (node.js:407:9)
  at process._tickCallback (node.js:336:13)
```

Need to manually restart the tests in travis very often, although the code is fine.

**Comment by ducin** [comment]
`mixin issues with allOf (core/issues/issue-57.json) should get combined as expected` might still be randomly failing, need to check that.

**Comment by ducin** [comment]
@pateketrueke I'l help you. Keep clicking until generate on [this one](http://json-schema-faker.js.org/#%7B%22definitions%22%3A%7B%22address%22%3A%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22street_address%22%3A%7B%22type%22%3A%22string%22%7D%2C%22city%22%3A%7B%22type%22%3A%22string%22%7D%2C%22state%22%3A%7B%22type%22%3A%22string%22%7D%7D%2C%22required%22%3A%5B%22street_address%22%2C%22city%22%2C%22state%22%5D%7D%7D%2C%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22billing_address%22%3A%7B%22%24ref%22%3A%22%23%2Fdefinitions%2Faddress%22%7D%2C%22shipping_address%22%3A%7B%22allOf%22%3A%5B%7B%22%24ref%22%3A%22%23%2Fdefinitions%2Faddress%22%7D%2C%7B%22properties%22%3A%7B%22type%22%3A%7B%22enum%22%3A%5B%22residential%22%2C%22business%22%5D%7D%7D%2C%22required%22%3A%5B%22type%22%5D%7D%5D%7D%7D%7D) until you get `{}`.

**Comment by pateketrueke** [comment]
Proudly closed! 🍻
