### ISSUE TITLE
【0.5.0-rc6】$ref bug

### ISSUE THREAD

**Issue by mansonchor** [json-schema-faker/json-schema-faker#294]
version: 0.5.0-rc6

```js
// test.js
const jsf = require('json-schema-faker');

const references = [{
  id: 'a',
  type: 'string',
}, {
  id: 'b',
  type: 'object',
  properties: {
    a: { '$ref': 'a' },
  },
  required: ['a'],
}, {
  id: 'c',
  type: 'object',
  properties: {
    b: { '$ref': 'b' },
  },
  required: ['b'],
}];

const parseSchema = {
  type: 'object',
  properties: {
    b: { '$ref': 'b' },
    c: { '$ref': 'c' },
  },
  required: ['b', 'c'],
};

const res = jsf(parseSchema, references);

console.log(res);
```

expect

```js
{ b: { a: 'est sed commodo laboris id' },
  c: { b: { a: 'ullamco sint ipsum' } } }
```

but actully I get an error throw

```shell
Error: Reference not found: http://json-schema.org/a#
    at reduce (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:986:27)
    at reduce (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:1017:33)
    at reduce (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:1017:33)
    at reduce (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:1017:33)
    at reduce (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:1017:33)
    at reduce (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:1017:33)
    at reduce (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:1017:33)
    at traverse (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:903:14)
    at run (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:971:16)
    at jsf (/Users/manson/uc_project/panda/panda/node_modules/_json-schema-faker@0.5.0-rc6@json-schema-faker/lib/index.js:1049:12)
```

----

# By the way

I Find `jsf@0.5.0-rc` too unstable. At least 3+ bug I had submit in this rc-version

consider set the `npm dist-tag lastest` to `0.4.2` stable version, and `next` to `0.5.0-rc`?

**Comment by pateketrueke** [comment]
Thanks for your feedback, I'll change the latest/next tags asap.

For dereferencing we rely on `deref` and `json-schema-ref-parser` for most dereferencing, `jsf()` and `jsf.resolve()` for sync/async support respectively.

Try to use `jsf.resolve()` instead and see if it works for you.

Anyway I think your references are enough simple and should be dereferenced without issues, I'll investigate this further.

**Comment by pateketrueke** [comment]
Fixed on RC7
