### ISSUE TITLE
It is impossible to work with $ref for local files

### ISSUE THREAD

**Issue by makhnatkin** [json-schema-faker/json-schema-faker#370]
1) I'm using a json-schemas generator from Excel file: https://github.com/pponugo/excel2jsonschema.
2) As a result of the generator I get such files with  json-schemas:

```
// get-list.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "getList",
    "description": "getList",
    "type": "object",
    "properties": {
        "request": {
            "description": "Request",
            "$ref": "request.json#"
        },
        "response": {
            "description": "Response",
            "type": "array",
            "items": {
                "$ref": "response.json#"
            }
        }
    },
    "required": []
}

// request.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Request",
    "description": "Request",
    "type": "object",
    "properties": {
        "query": {
            "type": "string"
        }
    },
    "required": []
}

// response.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Response",
    "description": "Response",
    "type": "object",
    "properties": {
        "accesstypeid": {
            "type": "string"
        }
    },
    "required": []
}
```
3) Next, I put all the files in the folder: src/api/test and run a script node scripts/gen.js for get-list.json that does `jsf(schema.properties.response) `on Windows. json-schema-faker@0.5.0-rc12

**Expected result:**
Moks generated.

**Actual result:**
```
 node scripts/gen.js

C:\Users\some\ui\node_modules\deref\lib\util\find-reference.js:46
    throw new Error('Reference not found: ' + id);
    ^

Error: Reference not found: http://json-schema.org/api/test/response#
    at module.exports (C:\Users\some\ui\node_modules\deref\lib\util\find-reference.js:46:11)
    at copy (C:\Users\some\ui\node_modules\deref\lib\util\resolve-schema.js:18:19)
    at copy (C:\Users\some\ui\node_modules\deref\lib\util\resolve-schema.js:41:22)
    at Object.module.exports [as resolveSchema] (C:\Users\some\ui\node_modules\deref\lib\util\resolve-schema.js:54:10)
    at $ref (C:\Users\some\ui\node_modules\deref\lib\index.js:63:14)
    at jsf (C:\Users\some\ui\node_modules\json-schema-faker\lib\index.js:1345:23)
    at getMock (C:\Users\some\ui\node_modules\gen.js:15:58)
    at Array.map (native)
    at getMocks (C:\Users\some\ui\scripts\gen.js:14:76)
    at C:\Users\some\ui\scripts\gen.js:29:17
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Additional info:**

Mocks on this scheme are generated perfectly:

```
// get-list-without-ref.json

{
    "id": "/api/test/get-list",
    "title": "getList",
    "description": "getList",
    "type": "object",
    "properties": {
        "request": {
            "title": "Request",
            "description": "Request",
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                }
            },
            "required": []
        },
        "response": {
            "description": "Some",
            "type": "array",
            "items": {
                "title": "Response",
                "description": "Response",
                "type": "object",
                "properties": {
                    "accesstypeid": {
                        "type": "string"
                    }
                },
                "required": []
            }
        }
    },
    "required": ["request", "response"]
}
```

**BUT: I have not found a way to cut this scheme into 3 files and put them side by side locally so that you can use $ref. I also analyzed the deref code and documentation, but could not implement such a case.**

**Comment by pateketrueke** [comment]
Can you share the code from the `scripts/schemas2mocks.js` file? 🤔

**Comment by Oleg2tor** [comment]
As far you using v0.5.x version you should use corresponding api, so instead:
`jsf(schema.properties.response)`
use:
`jsf.resolve(schema.properties.response, 'ref URI here')`

**Comment by makhnatkin** [comment]
@Oleg2tor thx, its works fine
