### ISSUE TITLE
Circular referencies not working?

### ISSUE THREAD

**Issue by pateketrueke** [json-schema-faker/json-schema-faker#427]
The gist: https://json-schema-faker.js.org/#gist/bb50a5c991ce20d8ae783a7bbd435c02/0.5.0-rc15

> Follow the `$comment` from the given schema to see what happens.

- Expected: the `b` propertie should be faked
- Actual result: `b` is not faked anymore due circular-refs?

**Comment by erraggy** [comment]
I believe this is also manifesting when using `oatts generate` (see [Oatts](https://google.github.io/oatts/)) when the swagger json source contains `$ref` values that point to ancestors of the holder of the `$ref` field.

In my case the issue manifests as:
```
17:21 $ oatts generate -s http://localhost:8001/api/api-docs.json -w oatts/generated/
Error: JSON pointer not found: http://json-schema.org/schema#/definitions/domain.QueryRequest
    at get (/usr/local/lib/node_modules/oatts/node_modules/deref/lib/util/find-reference.js:14:13)
    at Object.module.exports [as findByRef] (/usr/local/lib/node_modules/oatts/node_modules/deref/lib/util/find-reference.js:27:38)
    at reduce (/usr/local/lib/node_modules/oatts/node_modules/json-schema-faker/lib/jsf.js:40:27)
    at traverse (/usr/local/lib/node_modules/oatts/node_modules/json-schema-faker/lib/util/traverse.js:10:3)
    at module.exports (/usr/local/lib/node_modules/oatts/node_modules/json-schema-faker/lib/util/traverse.js:61:19)
    at generate (/usr/local/lib/node_modules/oatts/node_modules/json-schema-faker/lib/jsf.js:19:12)
    at Parameter.getSample (/usr/local/lib/node_modules/oatts/node_modules/sway/lib/types/parameter.js:94:39)
    at /usr/local/lib/node_modules/oatts/lib/process.js:263:75
    at Array.forEach (<anonymous>)
    at processParams (/usr/local/lib/node_modules/oatts/lib/process.js:259:24)
```
Is thrown for a json structure like so:
```
{
    "swagger": "2.0",
    "info": {
        "title": "MyAPI",
        "version": "1.0.0"
    },
    "paths": {
        "/api/queries/products": {
            "post": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "summary": "Query products.",
                "operationId": "QueryProducts",
                "parameters": [{
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/domain.QueryRequest"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.QueryReponse"
                        }
                    },
                    "default": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.QueryReponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.QueryRequest": {
            "required": ["name", "type", "filter", "sub_queries"],
            "properties": {
                "filter": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sub_queries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.QueryRequest"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.QueryReponse": {
            "required": ["status", "total_results"],
            "properties": {
                "status": {
                    "type": "string"
                },
                "total_results": {
                    "type": "integer"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
```

**Comment by pateketrueke** [comment]
Fixed on `develop`? 💣
