### ISSUE TITLE
"Error while resolving schema" - dependent on seed

### ISSUE THREAD

**Issue by st-fankl-in** [json-schema-faker/json-schema-faker#655]
I encountered random errors while generating data, so I tried to isolate the error.

```
const jsf = require('json-schema-faker')
const faker = require('faker')

jsf.option({
  random: () => faker.datatype.float({max: 1})
})

const gen = async() => {
  const schema = require(`./schema/array`)
  try {
    const doc = await jsf.resolve(schema, null, './schema')
    console.log('success', doc)
  } catch (e) {
    console.log('error', e)
  }
}

const main = async() => {
   for (x of [1, 4, 1061, 1054, 1043 ]) {
    console.log(x, 'results in:')
    faker.seed(x)
    await gen()
  }
}

main()
```
Schema:
```
{
  "type": "object",
  "properties": {
    "foo": {
      "$ref" : "defs.json#/definitions/stringArray"
    }
  }
}

```
definition
```
{
  "definitions": {
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 1
    }
  }
}

```

The seeds 1 & 1043 work as expected, while the other examples result in:

`Error: Error while resolving schema (TypeError: Cannot read property 'low' of undefined ...`

In case it matters, running this on node 12.22.1

**Comment by pateketrueke** [comment]
Which version of faker you're using? Also, can you share the whole error-stack? Thank you!

**Comment by st-fankl-in** [comment]
Hi,

faker is version 5.5.3, 
json-schema-faker is 0.5.0-rcv.34

And the error-stack:
```
Error while resolving schema (TypeError: Cannot read property 'low' of undefined
    at DRange.index (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:780:31)
    at RandExp._randSelect (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:971:18)
    at RandExp._gen (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:915:41)
    at RandExp._gen (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:924:23)
    at RandExp._gen (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:900:23)
    at RandExp.gen (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:870:17)
    at Object._randexp [as randexp] (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:1089:13)
    at hash (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:2296:48)
    at Object.objectType [as object] (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:2352:70)
    at traverse (/home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:2686:29) in /)
    at /home/stefan/devel/schema-bug/node_modules/json-schema-faker/dist/main.cjs.js:3107:13
    at async gen (/home/stefan/devel/schema-bug/index.js:11:17)
    at async main (/home/stefan/devel/schema-bug/index.js:22:5)
```

When I set 'additionalProperties' to false on the object, I wasn't able to trigger the issue (yet?).

regards,
Stefan

**Comment by pateketrueke** [comment]
I tracked down the error on the stack and noticed that disabling `fillProperties` the error is gone, we use RandExp to generate random properties on the target object.

I'm still unsure what's happening behind, but also I found that `faker.datatype.float({max: 1})` would return, sometimes, 1 as result and after that the brokes... but not always, so is not deterministic.

We could try to figure out what's happening, but I think is outside jsf scope, if we can isolate the issue related to faker and randexp then we could open some issues respectively.

**Comment by pateketrueke** [comment]
Closing as stale — no reproduction has been provided and the issue has been open for years without activity.
