### ISSUE TITLE
The sourcemap settings seem incorrect and break error stack message

### ISSUE THREAD

**Issue by JounQin** [json-schema-faker/json-schema-faker#671]
```log
Error: Error: unknown registry key "int-or-string"
    at generateFormat (/Users/alvaro/Workspace/json-schema-faker/src/lib/types/Users/alvaro/Workspace/json-schema-faker/src/lib/types/string.js:49:17)
    at /Users/alvaro/Workspace/json-schema-faker/src/lib/types/Users/alvaro/Workspace/json-schema-faker/src/lib/types/string.js:63:14
    at Object.typecast (/Users/alvaro/Workspace/json-schema-faker/src/lib/core/Users/alvaro/Workspace/json-schema-faker/src/lib/core/utils.js:132:15)
    at Object.stringType [as string] (/Users/alvaro/Workspace/json-schema-faker/src/lib/types/Users/alvaro/Workspace/json-schema-faker/src/lib/types/string.js:61:24)
    at traverse (/Users/alvaro/Workspace/json-schema-faker/src/lib/core/Users/alvaro/Workspace/json-schema-faker/src/lib/core/traverse.js:130:35)
    at /Users/alvaro/Workspace/json-schema-faker/src/lib/core/Users/alvaro/Workspace/json-schema-faker/src/lib/core/traverse.js:172:48
    at Array.forEach (<anonymous>)
    at traverse (/Users/alvaro/Workspace/json-schema-faker/src/lib/core/Users/alvaro/Workspace/json-schema-faker/src/lib/core/traverse.js:169:23)
    at Object.objectType [as object] (/Users/alvaro/Workspace/json-schema-faker/src/lib/types/Users/alvaro/Workspace/json-schema-faker/src/lib/types/object.js:260:10)
    at traverse (/Users/alvaro/Workspace/json-schema-faker/src/lib/core/Users/alvaro/Workspace/json-schema-faker/src/lib/core/traverse.js:130:35) in /properties/spec/properties/ports/items/1/properties/targetPort
    at run (/Users/alvaro/Workspace/json-schema-faker/src/lib/core/Users/alvaro/Workspace/json-schema-faker/src/lib/core/run.js:115:13)
    at Function.jsf.generateWithContext (/Users/alvaro/Workspace/json-schema-faker/src/lib/Users/alvaro/Workspace/json-schema-faker/src/lib/index.js:99:10)
    at jsf.generate (/Users/alvaro/Workspace/json-schema-faker/src/lib/Users/alvaro/Workspace/json-schema-faker/src/lib/index.js:103:9)
    at mockFromSwagger (/Users/JounQin/Workspaces/Alauda/vision/server/utils/swagger.ts:213:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /Users/JounQin/Workspaces/Alauda/vision/server/middlewares/mock.ts:92:24
```

Who is `alvaro`? I have no idea.

**Comment by pateketrueke** [comment]
Oh, my name's alvaro btw; sorry for pushing those into the repo, but as they are not yet released I though it could be acceptable :)

**Comment by JounQin** [comment]
> Oh, my name's alvaro btw; sorry for pushing those into the repo, but as they are not yet released I though it could be acceptable :)

It is the npm version.

**Comment by pateketrueke** [comment]
My bad

**Comment by pateketrueke** [comment]
I found that even when sourcemaps are generated correctly they still point to my local workspace, what do you think is the correct thing to do? 

I mean, I can omit sourcemaps on the built files, so the stack trace should point to the `dist/` files as expected.

**Comment by JounQin** [comment]
I'm not familiar with the code base, and just look through `package.json` quickly. The project is built with `mortero`, but I have no idea what it is and on source code can be found. It should be a bug of `mortero` or its dependencies IMO.

Before we found out what is the root cause, the incorrect source map should be omitted, so that the error stack is correct at least.

**Comment by pateketrueke** [comment]
I'm using `esbuild` (mortero is a wrapper I wrote) to bundle the library, and also noticed that some sources have a segment repeated, e.g. `src/lib/src/lib/index.js`

I'll disable the source maps for the generated `dist/` files while looking for the root-cause, thank you!

**Comment by pateketrueke** [comment]
I found the reason behind the duplicated path, it's gone, however generated source paths are like `src/lib/types/string.js` but in the stacktrace they are appended to the `dist/` folder:

```
Error: Error: unknown registry key "whatever"
    at generateFormat (/Users/alvaro/Workspace/json-schema-faker/dist/src/lib/types/string.js:49:17)
```

**Comment by pateketrueke** [comment]
Current release does not ship the sourcemaps anymore, you'll get the default stacktrace instead.
