### ISSUE TITLE
Refs not working in root schema

### ISSUE THREAD

**Issue by JoshuaWise** [json-schema-faker/json-schema-faker#687]
Using this schema:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
        "bar": { "type": "string" }
      }
    }
  },
  "$ref": "#/definitions/foo"
}
```

I expected it to resolve the `$ref`, but instead I got this error:

```
Reference not found: #/definitions/foo
```

**Comment by pateketrueke** [comment]
Which version are you using? 🤔

**Comment by JoshuaWise** [comment]
version `0.5.0-rcv.40`

**Comment by pateketrueke** [comment]
Can you share more details? The same schema seems to be working online, thank you!

**Comment by JoshuaWise** [comment]
### Steps to reproduce:

1. `mkdir example`
2. `cd example`
3. `npm init -y`
4. `npm install json-schema-faker`
5. create a file called `test.js` with the following content: 
```js
const jsf = require("json-schema-faker");

const result = jsf.generate({
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "foo": {
      "type": "object",
      "properties": {
        "bar": { "type": "string" }
      }
    }
  },
  "$ref": "#/definitions/foo"
});

console.log(result);
```
6. `node test.js`


### Result:

```
~/Desktop/code/example$ node test.js 
/Users/josh/Desktop/code/example/node_modules/json-schema-faker/dist/main.cjs.js:2414
          throw e;
          ^

Error: Reference not found: #/definitions/foo
    at recursiveUtil.resolveSchema (/Users/josh/Desktop/code/example/node_modules/json-schema-faker/dist/main.cjs.js:2257:21)
    at traverse (/Users/josh/Desktop/code/example/node_modules/json-schema-faker/dist/main.cjs.js:2079:16)
    at run (/Users/josh/Desktop/code/example/node_modules/json-schema-faker/dist/main.cjs.js:2402:24)
    at Function.jsf.generateWithContext (/Users/josh/Desktop/code/example/node_modules/json-schema-faker/dist/main.cjs.js:6084:14)
    at Function.jsf.generate (/Users/josh/Desktop/code/example/node_modules/json-schema-faker/dist/main.cjs.js:6086:51)
    at Object.<anonymous> (/Users/josh/Desktop/code/example/test.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
```

### `npm list`

```
~/Desktop/code/example$ npm list
example@1.0.0 /Users/josh/Desktop/code/example
└─┬ json-schema-faker@0.5.0-rcv.40
  ├─┬ json-schema-ref-parser@6.1.0
  │ ├── call-me-maybe@1.0.1
  │ ├─┬ js-yaml@3.14.1
  │ │ ├─┬ argparse@1.0.10
  │ │ │ └── sprintf-js@1.0.3
  │ │ └── esprima@4.0.1
  │ └─┬ ono@4.0.11
  │   └── format-util@1.0.5
  └── jsonpath-plus@5.1.0
```

**Comment by pateketrueke** [comment]
Awesome, thank you! We'll be working on fixing this asap.
