### ISSUE TITLE
Make faker dependency optional

### ISSUE THREAD

**Issue by hellboy81** [json-schema-faker/json-schema-faker#69]
In my fakes for unit tests only `chance` library is used to generate both fake values (strings, numbers etc) and object from JSON scheme.

```js
var jsf     = require('json-schema-faker'),
    chance  = require('chance').Chance() // And no faker dependency
```

Why `faker` dependency is still required by `json-schema-faker`?

```
`module.js:340
    throw err;
          ^
Error: Cannot find module 'faker'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../node_modules/json-schema-faker/lib/util/container.js:8:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../node_modules/json-schema-faker/lib/index.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../test/unit/fakes/index.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../test/unit/addon/module.private.spec.js:7:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at .../node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (.../node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (.../node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (.../node_modules/mocha/bin/_mocha:401:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by pateketrueke** [comment]
Take a look to #56 you can easily build while *faking* the *faker* module to an empty one?

**Comment by pateketrueke** [comment]
Hi again, I've been working on fixing issues related with bundling, and I understand you issue now.

It's true that `json-schema-faker` use `faker` for a few helpers that aren't built-in.

In order to mitigate that we could try creating a wrapper for those basic stuff like `faker.random.number` and `faker.random.words`, then detect which support is already installed and use it.

Probably a edge case could be using jsf without dependencies (randexp is still required due the `pattern` keyword), so we need to implement a micro-faker version for providing the helpers mentioned above.

Sorry for the lack of attention in this issue.

:beers:

**Comment by hellboy81** [comment]
OK, at the moment I should install  both `chance` and `faker` dependencies in my own service to use it with `json-schema-faker`?

**Comment by ducin** [comment]
which version of jsf are you using?

**Comment by hellboy81** [comment]
The last one: `0.2.13`

**Comment by pateketrueke** [comment]
> OK, at the moment I should install both chance and faker dependencies in my own service to use it with json-schema-faker?

No, until `0.3.0` we will continue shipping `faker` and `chance` as `dependencies` in our `package.json` definition.
