### ISSUE TITLE
Error: TypeError: Cannot destructure property 'value' of 'traverse(...)' as it is undefined.

### ISSUE THREAD

**Issue by Emdave10** [json-schema-faker/json-schema-faker#710]
code:
`jsf.generate({ $ref: 'SampleSchema.json' }, refs)`

When i use the above code to generate sample data for my schema which has some $ref's it works sometimes and sometimes it throws the error below : `Error: TypeError: Cannot destructure property 'value' of 'traverse(...)' as it is undefined.` I am not sure why this is happening but it could be as a result of when resolving the refs and destructuring them to generate the sample data it is encountering an object or propoerty which is {} and undefined, which is based on the schemas type resulting to the error above. I may be wrong but if anyone knows a fix to this issue, It will be very much appreciated. Btw, sometimes it works and sometimes it gives that error, just thought to highlight that

**Comment by pateketrueke** [comment]
It is hard to understand without knowing all the related schemas, please share them, probably you're trying to reference something that is not actually present (hence the undefined result).

**Comment by Emdave10** [comment]
Since i have alot of sub schema's, I will narrow down to where the error occurs and share it, probably that would be easier for you to help spot where exactly the error is coming from. Thanks in advance

**Comment by Emdave10** [comment]
Also wanted to highlight that this tool is really helpful to me and one thing i may need more insight on is how exactly circular references are avoided when generating sample data as its very impressive. Most tools just leave a tag highlighting the circular references and not resolve them properly, but how did you work around circular references to further generate data for them. Ive just been a bit curious and will be glad if you can enlighten me a bit on it *some extra knowledge not a issue*

**Comment by Emdave10** [comment]
> It is hard to understand without knowing all the related schemas, please share them, probably you're trying to reference something that is not actually present (hence the undefined result).

I have done my investigations and the problem is not from any of the schemas. If i did try to reference something that is not present the error code will be different, it will be this instead : `Error: Error: Reference not found: Schema.json` but this time it is something different which makes me convinced that it is a bug. I have a lot of sub schemas and its impossible to share the schemas but i am pretty sure its not the schemas, heres the full log of the error i receive: 
```
/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:2415
          throw new Error(`${e.message} in /${e.path.join("/")}`);
          ^

Error: TypeError: Cannot destructure property 'value' of 'traverse(...)' as it is undefined.
    at /projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:2191:19
    at Array.forEach (<anonymous>)
    at traverse (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:2187:27)
    at /projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:2191:52
    at Array.forEach (<anonymous>)Img
    at traverse (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:2187:27)
    at Object.objectType [as object] (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:1851:14)

    at traverse (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:2158:44)
    at traverse (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:2117:50)
    at Object.arrayType [as array] (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:1567:25) in /properties/values/items/0/properties/instances/items/0/properties/values/items/3/properties/constraints/items/2

    at run (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:2415:17)
    at Function.jsf.generateWithContext (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:6087:14)
    at Function.jsf.generate (/projects/JS/Img/node_modules/json-schema-faker/dist/main.cjs.js:6089:51)
    at /projects/JS/Img/JsonSchemaGen.js:200:18
    at /projects/JS/Img/node_modules/call-me-maybe/index.js:11:28
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by pateketrueke** [comment]
Hi, I just pushed a commit that would help us debugging on this, can you install this module from the develop branch instead? Thank you!

**Comment by Emdave10** [comment]
> Hi, I just pushed a commit that would help us debugging on this, can you install this module from the develop branch instead? Thank you!

I have done that and after testing, the times that random data generation failed, some of the errors obtained were as follows: 
```
Error: Error: Cannot traverse at 'properties.condition.default', given 
'{"info":["The condition for presence.",["Conditions are unique,",
"Because of true condition."],"condition present."]}'

Error: Error: Cannot traverse at 'properties.values.items.1.properties.instances.items.0.properties.values.items.1.properties.fields.items.2.properties.field.properties.access.default', given '{}'

Error: Error: Cannot traverse at 'properties.values.items.2.properties.fieldss.items.1.properties.condition.default', given '{"info":["condition present."]}'
```

Having done what you said i was able to figure out where the first error was coming from with the help of the new error log, and as you can see with the little snippet of the schema i am trying to generate random data for, we can see that the schema has some external refs which have been referenced with the id's of other loaded schemas instead of their file paths as shown below, but the question is I dont know why such error is occuring as it works sometimes and doesn't. A little snippet of the schema im using is attached below (little snippet as the main schema is too large to share)

```
{
    "$id": "Fieldssip.json",
    "$schema": http://jsonn-schem.org/d/schema#,
    "additionalProperties": false,
    "info": [
        "An array container",
        [
            "If a fieldset is used inside an context of an array, then the condition property is used",
            "to define conditional layouts"
        ]
    ],
    "properties": {
        "_meta": {
            "$ref": "Meat.json",
            "info": "Meat"
        },
        "_type": {
            "enum": [
                "Fieldssip"
            ]
        },
        "condition": {
            "$ref": "Trip_Condition.json#/definitions/condition",
            "info": [
                  "The condition for presence.",
                  [
                  "Conditions are unique." , "Because of true condition."
                   ],
                  "condition present."
            ]
        }
    }
}
```

I really appreciate the help

**Comment by Emdave10** [comment]
> I think the traverse function is eating more that it should... unknown properties should be left as is, let me figure it out.

Thank you very much, would be waiting on a fix

**Comment by pateketrueke** [comment]
@Emdave10 there's a way you can share a minimal repro of this issue including the used schemas? I hasn't be able to reproduce it yet... thank you!
