### ISSUE TITLE
Error: TypeError: Cannot convert undefined or null to object  at Function.keys (<anonymous>)   at merge 

### ISSUE THREAD

**Issue by akshaymantriwar** [json-schema-faker/json-schema-faker#799]
While upgrading the **_Node from 14 to 16(Node 16 and npm 8.19.4)_**, I was getting primitive type issues 
![image](https://github.com/json-schema-faker/json-schema-faker/assets/25244758/58f2d302-e4d3-413d-b62c-8502612de37e)
So I resolved those  them while I am generating the schema 
`
jsf.generate(schema)`

I am getting below issue 

```
An error occurred, but we are ignoring it: Error: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at merge (C:\Code\upp-app\node_modules\json-schema-faker\dist\main.cjs:1180:10)
    at C:\Code\upp-app\node_modules\json-schema-faker\dist\main.cjs:1187:23
    at Array.forEach (<anonymous>)
    at C:\Code\upp-app\node_modules\json-schema-faker\dist\main.cjs:1185:14
```

![image](https://github.com/json-schema-faker/json-schema-faker/assets/25244758/a2d39736-a6a0-44c2-a42c-6a8828562e61)

Actually the confusion is It was working in Node 14 and npm 6, why is it not working now? Any update needs to be done?

**Comment by pateketrueke** [comment]
I am afraid of the error "unkown primitive String" because that could mean you mistyped "string", but without the real code you're using is hard to think about.

Please share the exact code you're using to help us understand, thank you!

**Comment by akshaymantriwar** [comment]
UNknown Primitive is not a actual problem, we have resolved it by changing it to string from String

We are getting TypeError: Cannot convert undefined or null to object at  **_jsf.generate(schema);_**

```
const generateReportFromSchema = (id, type) => {
  jsf.extend("faker", () => {
    faker.custom = extensions.custom;
    return faker;
  });
  jsf.format("simpleValue", simpleValue);
  const schema = generateReportSchema(id);
  return jsf.generate(schema);   //Here we are getting null object issue
};
```

```
const generateReportSchema = id => {
  const country = "US" + id;

  const schema = {
    $schema: "http://json-schema.org/draft-07/schema#",
    properties: {
      companyId: {
        type: "string",
        enum: [id],
      },
      typeOfOffice: {
        type: "string",
        enum: country === "IT" ? ["head", "other"] : ["Head"],
      },
    },
    required: ["companyId", "officeType"],
  };
};
```

**Comment by akshaymantriwar** [comment]
@pateketrueke  Can you please suggest any solution

**Comment by pateketrueke** [comment]
Do you have a reproduction of this issue? TBH having to reproduce every issue by hand takes time, please help me to help you!

**Comment by akshaymantriwar** [comment]
@pateketrueke  We have created reproducible case on https://stackblitz.com/edit/stackblitz-starters-mlcce4 
Can you please check.

**Comment by pateketrueke** [comment]
Closing as user error. The `generateReportSchema` function referenced in the schema is missing a `return` statement, causing it to return `undefined`. This is not a library bug.
