### ISSUE TITLE
Browser.process evaluated as true in `vendor.js` when run in a Node environment

### ISSUE THREAD

**Issue by madi-tracksuit** [json-schema-faker/json-schema-faker#800]
When running `JSONSchemaFaker` in a node environment I get the following error

```
ReferenceError: location is not defined
```

Suggesting something thinks it's in a browser environment. Digging into the stacktrace shows that `browser.process` checks done in `vendor.js` are evaluated as `true`, when checking `browser.process` in the script that calls `JSONSchemaFaker` evaluates correctly as `undefined`. 

From reading the docs it sounds like `vendor.js` shouldn't even be used or imported when in a Node envrionment. 

Extra details:
- Node v20
- ESM module
- Whole schema in one JS object, no local refs to resolve

Full stacktrace of original error

```
ReferenceError: location is not defined
    at exports.cwd (file:///{...}/node_modules/json-schema-faker/dist/vendor.js:9:21639)
    at $RefParser.parse (file:///{...}/node_modules/json-schema-faker/dist/vendor.js:9:5371)
    at $RefParser.resolve (file:///{...}/node_modules/json-schema-faker/dist/vendor.js:9:6027)
    at $RefParser.bundle (file:///{...}/node_modules/json-schema-faker/dist/vendor.js:9:6429)
    at $RefParser.bundle (file:///{...}/node_modules/json-schema-faker/dist/vendor.js:9:6313)
    at jsf.resolveWithContext (file:///{...}/node_modules/json-schema-faker/dist/shared.js:6159:21)
    at jsf.resolve (file:///{...}/node_modules/json-schema-faker/dist/shared.js:6172:42)
    at file:///{...}/scripts/build.js:64:40
```

**Comment by pateketrueke** [comment]
I found a workaround while we patch the library:

```js
global.location = new URL(import.meta.url);

import { JSONSchemaFaker } from 'json-schema-faker';
```

**Comment by madi-tracksuit** [comment]
Workaround works well, thanks!

**Comment by ahpkadota** [comment]
Just as an update, this error might be related to issue #828 

I'm using Node 23. I tried to override the outdated "json-schema-ref-parser": "^6.1.0" for the latest version "@apidevtools/json-schema-ref-parser": "^11.9.3". 

in json-schema-faker/dist/main.mjs:
> import './vendor.js';
import $RefParser from "@apidevtools/json-schema-ref-parser"
import { setDependencies } from './shared.js';
/* global $RefParser, JSONPath */
if (typeof $RefParser !== 'undefined' && typeof JSONPath !== 'undefined') {
  setDependencies({ ...JSONPath, $RefParser });
}
export { default, JSONSchemaFaker } from './shared.js';
 

The "ReferenceError: location is not defined" error was gone. Just posting in case this helps!

kudos for the repo
