### ISSUE TITLE
Hangs with circular references 

### ISSUE THREAD

**Issue by blikblum** [json-schema-faker/json-schema-faker#92]
When i try the following schema:  https://gist.github.com/blikblum/5c90d02a99b3f3b9c017#file-data-schema-json [changed to avoid the circular reference, see comment below for example]

JSON Schema Faker becomes unresponsive, consuming all cpu time and is necessary to kill its process.

This occurs both with the online demo and using node 4.2.4

Tested with 0.2.8

**Comment by blikblum** [comment]
The issue is caused by the circular reference of `track.variations.tracks -> track"`

The schema below is the minimal example that hangs
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "$ref": "#/definitions/track"
  },
  "definitions": {
    "track": {
      "type": "object",
      "required": [
        "variations"
      ],
      "properties": {
        "variations": {
          "type": "object",
          "properties": {
            "count": {
              "type": "integer"
            },
            "tracks": {
              "type": "array",
              "items": {
                "type": "object",
                "required" : ["tracks"],
                "properties": {
                  "tracks": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/track"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

It leads to an infinite loop at
```
merge(sub, $.util.findByRef(id, $.refs)); 
```
I acknowledge that this tool is not supposed to handle such case (I'm not sure if is a valid schema at all) the only thing that could be improved is detecting the circular reference and halts with a message

**Comment by pateketrueke** [comment]
I think it's a valid schema, although a recursive one, let me see what can I do.

**Comment by blikblum** [comment]
Syntax wide it can be a valid schema, but is impossible to have a value that matches this schema

track require variations which require tracks require track which require variations

**Comment by tauren** [comment]
Would love to see the fix for this get published to npm! What is the status (and purpose) of the `npm-scripts` branch? Will it get integrated into master sooner or later?

BTW, the following module appears to handle circular references. I'm not sure if it would help, but perhaps it could be used instead of `deref`?:
https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/docs/README.md#circular-refs

**Comment by pateketrueke** [comment]
The npm-scripts PR should be merged asap (once I fix some coveralls issues we had) because has very improvements to dev/test/build tasks.

Yeah, we could use `json-schema-ref-parser` which looks awesome!, but since jsf has no async support it will take a bit more of time. :+1:

**Comment by tauren** [comment]
@pateketrueke Sounds great! However, I've been trying to use the `npm-scripts` branch with a circular schema that has been dereferenced with `json-schema-ref-parser` and I'm getting an error in `clone-obj.js`:

```
Error: unable dereference circular structures
    at module.exports (/Users/tmil11/stash/nidr/playbook-rulebook/node_modules/json-schema-faker/node_modules/deref/lib/util/clone-obj.js:7:11)
    at copy (/Users/tmil11/stash/nidr/playbook-rulebook/node_modules/json-schema-faker/node_modules/deref/lib/util/clone-obj.js:19:19)
    at /Users/tmil11/stash/nidr/playbook-rulebook/node_modules/json-schema-faker/node_modules/deref/lib/util/clone-obj.js:28:7
    at Array.forEach (native)
```

This may be due to my shemas, as I'm not convinced the `id` and `$ref` properties are setup up correctly. I'm working on figuring that out. 

Perhaps you could check `clone-obj.js` to see if there is something simple that might cause this as well?

**Comment by pateketrueke** [comment]
I've tested your schemas (from the gist) in the `npm-scripts` branch without `json-schema-ref-parser` and seems to be working:

```js
var schema = {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "minItems": 10,
  "maxItems": 10,
  "items": {
    "$ref": "#/definitions/track"
  },
  "definitions": {
    "path": {
      "type": "object",
      "required": [
        "wave_canvas",
        "wave_default",
        "wave_progress",
        "download_path",
        "audio",
        "watermarked"
      ],
      "properties": {
        "wave_canvas": {
          "type": "string"
        },
        "wave_default": {
          "type": "string"
        },
        "wave_progress": {
          "type": "string"
        },
        "download_path": {
          "type": "string"
        },
        "audio": {
          "type": "string"
        },
        "watermarked": {
          "type": "string"
        }
      }
    },
    "trackinfo": {
      "type": "object",
      "required": [
        "stems",
        "tracklength",
        "name",
        "apikey"
      ],
      "properties": {
        "stems": {
          "type": "string"
        },
        "tracklength": {
          "type": "string"
        },
        "inactive": {
          "type": "boolean"
        },
        "apikey": {
          "type": "string"
        },
        "audio_content_type": {
          "type": "string"
        },
        "geokey": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "staff_pick": {
          "type": "string"
        },
        "audio_file_size": {
          "type": "integer"
        },
        "audio_file_name": {
          "type": "string"
        },
        "lyrics": {
          "type": "string"
        },
        "bpm": {
          "type": "string"
        }
      }
    },
    "track": {
      "type": "object",
      "properties": {
        "mood": {
          "type": "string"
        },
        "direct_path": {
          "$ref": "#/definitions/path"
        },
        "variations": {
          "type": "object",
          "required": [
            "count",
            "direct_path",
            "tracks"
          ],
          "properties": {
            "count": {
              "type": "integer"
            },
            "direct_path": {
              "$ref": "#/definitions/path"
            },
            "tracks": {
              "type": "array",
              "minItems": 5,
              "maxItems": 5,
              "items": {
                "$ref": "#/definitions/trackinfo"
              }
            }
          }
        },
        "tag_list": {
          "type": "string"
        },
        "genre": {
          "type": "string"
        },
        "tempo": {
          "type": "string"
        },
        "instrument": {
          "type": "string"
        },
        "industry": {
          "type": "string"
        },
        "track": {
          "$ref": "#/definitions/trackinfo"
        }
      },
      "required": [
        "mood",
        "direct_path",
        "variations",
        "tag_list",
        "genre",
        "tempo",
        "instrument",
        "industry",
        "track"
      ]
    }
  }
};

// CWD from json-schema-faker
var jsf = require('./');

console.log(JSON.stringify(jsf(schema), null, 2));
```

(I's still considering to switch to `json-schema-ref-parser`)

**Comment by arjanvanderleden** [comment]
This does not work well with schemas like the one below. Would a maximal traversal depth not work better?

Test schema:
```

{
  "type": "object",
  "properties": {
    "firstUser": {
      "$ref": "#/definitions/Ci.IUser"
    },
    "secondUser": {
      "$ref": "#/definitions/Ci.IUser"
    },
    "thirdUser": {
      "$ref": "#/definitions/Ci.IUser"
    },
    "fourthUser": {
      "$ref": "#/definitions/Ci.IUser"
    },
    "fifthUser": {
      "$ref": "#/definitions/Ci.IUser"
    },
    "sixthUser": {
      "$ref": "#/definitions/Ci.IUser"
    },
    "seventhUser": {
      "$ref": "#/definitions/Ci.IUser"
    },
    "lastUser": {
      "$ref": "#/definitions/Ci.IUser"
    }
  },
  "required": [
    "firstUser",
    "secondUser",
    "thirdUser",
    "fourthUser",
    "fifthUser",
    "sixthUser",
    "seventhUser",
    "lastUser"
  ],
  "definitions": {
    "Ci.IUser": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "faker": "random.uuid"
        },
        "userName": {
          "type": "string",
          "faker": "internet.userName"
        },
        "firstName": {
          "type": "string",
          "faker": "name.firstName"
        },
        "lastName": {
          "type": "string",
          "faker": "name.lastName"
        },
        "email": {
          "type": "string",
          "faker": "internet.email"
        }
      },
      "required": [
        "_id",
        "userName",
        "firstName",
        "lastName",
        "email"
      ]
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}

```

resulting in: 

```
{
  "firstUser": {
    "_id": "6fdb3fe2-a7bc-4d70-a19c-bcd34fec3a1b",
    "userName": "Sanne99",
    "firstName": "Anne",
    "lastName": "Smit",
    "email": "Lisa.Willems71@hotmail.com"
  },
  "secondUser": {},
  "thirdUser": {},
  "fourthUser": {},
  "fifthUser": {},
  "sixthUser": {},
  "seventhUser": {},
  "lastUser": {}
}
```

**Comment by arjanvanderleden** [comment]
this would be my suggestion
replacing in jsf.js (line 19):

```
return traverse($(schema, refs, ex), [], function reduce(sub) {
  if (seen[sub.$ref] <= 0) {
	delete sub.$ref;
	delete sub.oneOf;
	delete sub.anyOf;
	delete sub.allOf;
	return sub;
  }

  if (typeof sub.$ref === 'string') {
	var id = sub.$ref;

	delete sub.$ref;

	if (!seen[id]) {
	  // TODO: this should be configurable
	  seen[id] = Number.MAX_VALUE;// random(1, 5);
	}

	seen[id] -= 1;

	merge(sub, $.util.findByRef(id, $.refs));
  }
```

with: 
	  
```
return traverse($(schema, refs, ex), [], function reduce(sub,maxReduceDepth) {
  if (typeof sub.$ref === 'string') {
	  var id = sub.$ref;
	  delete sub.$ref;          
	  if (typeof(maxReduceDepth)=='undefined') maxReduceDepth = 5;
	  if (maxReduceDepth<=0) {
		delete sub.$ref;
		delete sub.oneOf;
		delete sub.anyOf;
		delete sub.allOf;
		return sub;
	   }
	   maxReduceDepth -= 1;
	   merge(sub, $.util.findByRef(id, $.refs));              
  }
```
and in line 58 in jsf.js replacing
	`sub[prop] = reduce(sub[prop]);`
with 
	`sub[prop] = reduce(sub[prop],maxReduceDepth);`

that works for schema's like :

```
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "child": {
      "$ref": "#/definitions/Ci.IRecursiveTestJsf"
    },
    "otherChild": {
      "$ref": "#/definitions/Ci.IRecursiveTestJsf"
    }
  },
  "required": [
    "name",
    "child",
    "otherChild"
  ],
  "definitions": {
    "Ci.IRecursiveTestJsf": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "child": {
          "$ref": "#/definitions/Ci.IRecursiveTestJsf"
        },
        "otherChild": {
          "$ref": "#/definitions/Ci.IRecursiveTestJsf"
        }
      },
      "required": [
        "name",
        "child",
        "otherChild"
      ]
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

**Comment by ducin** [comment]
@arjanvanderleden thanks for this suggestion, we'll try to analyse it shortly. Would you create a PR with your suggestion? It'd be fired in CI/tests and it'sll be easier for us to maintain.

Thanks in advance!

**Comment by arjanvanderleden** [comment]
I have created a PR and also one for the “value.key.split is not a function” exception, if you’d like to merge that as well.
Thanks for your efforts, I think JSF is a great help en will speed up my UI development a lot.
Arjan

**Comment by FloNeu** [comment]
Was running into this issue with current version v0.5.0-rc15 and looking on a way to restrict the traversal depth property resolution... this is implemented by  this ticket? How can i use it, can't find documentation on this?

**Comment by pateketrueke** [comment]
Hi @FloNeu, please open an specific issue with the involved schema to analize it.

Thank you!

**Comment by FloNeu** [comment]
Hi! Will look into setting it up - for now i downgraded to release 4.6 which seemed to not having that issue.

**Comment by publicus** [comment]
First, thank you **very much** for your work on this project! I'm really grateful for the work you've put into it. What a great library.

This issue report follows https://github.com/json-schema-faker/json-schema-faker/issues/92#issuecomment-396583590. I'm running version `0.5.0-rc19`.

Using the following schema, which includes a circular reference, will cause the tab to hang / crash when `alwaysFakeOptionals` is checked.

<img width="437" alt="Screen Shot 2019-10-14 at 11 40 39 AM" src="https://user-images.githubusercontent.com/3667562/66764311-7e5c2e00-ee77-11e9-810e-700e6668d10c.png">

```
{
  "type": "object",
  "definitions": {
    "collectionDef": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "items": {
            "$ref": "#/definitions/aDef"
          },
          "type": "array"
        },
        "b": {
          "type": "string"
        }
      },
      "type": "object",
      "required": ["b", "a"]
    },
    "aDef": {
      "additionalProperties": true,
      "properties": {
        "subA": {
          "items": {
            "$ref": "#/definitions/aDef"
          },
          "type": "array"
        },
        "b": {
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "faker": "name.findName"
    },
    "email": {
      "type": "string",
      "faker": "internet.email"
    },
    "collection": {
      "$ref": "#/definitions/collectionDef"
    }
  },
  "required": ["name"]
}
```

**Actual result:** `json-schema-faker` hangs / generates data infinitely.

**Expected result:** From #129, is my understanding correct that `json-schema-faker` should *not* hang in this case, but rather should choose a "max. traversal depth" and stop generating data after going that number of levels deep?
